[workspace]
resolver = "3"
default-members = ["crates/dvrf-cli"]
members = [
  "crates/dvrf-cli",
  "crates/dvrf"
]

[workspace.package]
authors = ["Nico Wagner <n.wagner@dnb.de>"]
repository = "https://github.com/deutsche-nationalbibliothek/dvrf-rs"
license = "EUPL-1.2"
rust-version = "1.85"
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
clap = { version = "4.6.4", features = ["derive", "env"] }
dvrf = { path = "crates/dvrf", version = "0.1.0" }
flate2 = { version = "1.1.9" }
serde_json = { version = "1.0.151" }
serde = { version = "1.0.229", features = ["derive"] }


