[package]
name = "dvrf-cli"
description = "A command-line tool to process DVRF (Data Validation Report Format) files."
categories = ["command-line-utilities"]
keywords = ["code4lib"]

edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true
readme.workspace = true

[[bin]]
path = "src/main.rs"
name = "dvrf"

[[test]]
path = "tests/e2e/lib.rs"
name = "e2e"

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
dvrf = { workspace = true }
flate2 = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
predicates = { workspace = true }
